config/routes.rb
VotaPrato::Application.routes.draw do
  resources :comentarios

  resources :restaurantes

  resources :qualificacoes

  resources :clientes

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
	# relacionamentos
	has_many :comentarios, :as => :comentavel
	has_many :qualificacoes
	has_and_belongs_to_many :pratos

	# validações
	validates_presence_of :nome, 					:message => "deve ser preenchido"
	validates_presence_of :endereco, 			:message => "deve ser preenchido"
	validates_presence_of :especialidade, :message => "deve ser preenchido"

	validates_uniqueness_of :nome, 		 :message => "nome já cadastrado"
	validates_uniqueness_of :endereco, :message => "endereço já cadastrado"

	validate :primeira_letra_deve_ser_maiuscula

	private
		def primeira_letra_deve_ser_maiuscula
			errors.add("nome", "primeira letra deve ser maiúscula") unless nome =~ /[A-Z].*/
		end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  # GET /restaurantes
  # GET /restaurantes.xml
  def index
    @restaurantes = Restaurante.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @restaurantes }
    end
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.xml
  def show
    @restaurante = Restaurante.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @restaurante }
    end
  end

  # GET /restaurantes/new
  # GET /restaurantes/new.xml
  def new
    @restaurante = Restaurante.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @restaurante }
    end
  end

  # GET /restaurantes/1/edit
  def edit
    @restaurante = Restaurante.find(params[:id])
  end

  # POST /restaurantes
  # POST /restaurantes.xml
  def create
    @restaurante = Restaurante.new(params[:restaurante])

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to(@restaurante, :notice => 'Restaurante was successfully created.') }
        format.xml  { render :xml => @restaurante, :status => :created, :location => @restaurante }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @restaurante.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /restaurantes/1
  # PUT /restaurantes/1.xml
  def update
    @restaurante = Restaurante.find(params[:id])

    respond_to do |format|
      if @restaurante.update_attributes(params[:restaurante])
        format.html { redirect_to(@restaurante, :notice => 'Restaurante was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @restaurante.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.xml
  def destroy
    @restaurante = Restaurante.find(params[:id])
    @restaurante.destroy

    respond_to do |format|
      format.html { redirect_to(restaurantes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br />
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :especialidade %><br />
    <%= f.text_field :especialidade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/index.html.erb
<h1>Listing restaurantes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Endereco</th>
    <th>Especialidade</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @restaurantes.each do |restaurante| %>
  <tr>
    <td><%= restaurante.nome %></td>
    <td><%= restaurante.endereco %></td>
    <td><%= restaurante.especialidade %></td>
    <td><%= link_to 'Show', restaurante %></td>
    <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
    <td><%= link_to 'Destroy', restaurante, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurante', new_restaurante_path %>

app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @restaurante.nome %>
</p>

<p>
  <b>Endereco:</b>
  <%= @restaurante.endereco %>
</p>

<p>
  <b>Especialidade:</b>
  <%= @restaurante.especialidade %>
</p>

<b>Nota media: <%= @restaurante.qualificacoes.average(:nota) %></b>
<b>Qualificações: <%= @restaurante.qualificacoes.count %></b>
<b>Preço Medio: <%= @restaurante.qualificacoes.average(:valor_gasto) %></b>

<%= link_to "Qualificar este restaurante", :controller => "qualificacoes",
																 					 :action 		 => "new",
																 					 :cliente 	 => @restaurante %>

<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>